# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- ci

pool:
  vmImage: ubuntu-latest

container: 
  image: joelclems/geonature:latest

steps:

- script: |
    cp config/settings.ini.sample config/settings.ini
    . settings.ini
    cat config/settings.ini
  displayName: 'Settings'
 
- bash: |
    cat /etc/*-release
    id
  displayName: 'informations'

- script: |
    sudo apt-get install sudo
    sudo ls
  displayName: 'Test apt installsudo'

- script: |
    sudo apt install sudo wget postgresql postgresql-contrib curl unzip git
  displayName: 'Install deps'

- script: |
    cd install
    ./install_db.sh
  displayName: 'Install DB'
