# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- ci

pool:
  vmImage: ubuntu-latest

container: 
  image: geonature/debian:buster

steps:

- script: |
    cp config/settings.ini.sample config/settings.ini
    sed -i 's|mon.domaine.com|127.0.0.1|' install/install_all/install_all.ini
  displayName: 'Settings'
 
- bash: |
    cat /etc/*-release
    id
  displayName: 'informations'

# - bash: |
#     sudo apt update -y
#   displayName: 'test apt update'

# - bash: |
#     sudo apt install wget -y 
#   displayName: 'test apt install wget'

# - bash: |
#     sudo apt install wget postgresql postgresql-contrib curl unzip git -y
#   displayName: 'Install deps'

- bash: |
    cd install/intall_all
    ./install_all.sh
  displayName: 'Install DB'

