# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- ci

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    ubuntu18:
      containerImage: geonature/ubuntu:18.04
    debian9:
      containerImage: geonature/debian:stretch
    debian10:
      containerImage: geonature/debian:buster
      
container: $[ variables['containerImage'] ]

steps:

- bash: |
    cat /etc/*-release
    id
  displayName: 'system information'


- bash: |
    sed -i 's|mon.domaine.com|127.0.0.1|' install/install_all/install_all.ini
    sed -i 's|install_sig_layers=true|install_sig_layers=false|' install/install_all/install_all.ini
    sed -i 's|install_grid_layer=true|install_grid_layer=false|' install/install_all/install_all.ini
    sed -i 's|install_default_dem=true|install_default_dem=false|' install/install_all/install_all.ini
    sudo apt update -y
    cd install/install_all
    echo ./install_all.sh
  displayName: 'Install all'

- bash: |
    command -v python3.5
    a=$(command -v python3.5)
    echo test python 3.5 : __${a}__
  displayName: 'test python 3.5'

- bash: |
    sudo apt install -y git
    git clone https://github.com/PnX-SI/GeoNature-packaging.git
    cd GeoNature-packaging
    git checkout integration-testing
    cp settings.ini.sample settings.ini
    ./integration_tests.sh setup
    ./integration_tests.sh run_all
  displayName: 'Integration test'

