# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- ci

pool:
  vmImage: ubuntu-latest

container: 
  image: debian:stretch
    
steps:

- script: |
    cp config/settings.ini.sample config/settings.ini
    . settings.ini
    cat config/settings.ini
  displayName: 'Settings'

- bash: |
    echo release
    cat /etc/*-release
    echo
    echo id
    id
  displayName: 'informations'

- bash: |
    su
    apt install sudo
  displayName: 'Test apt installsudo'

- script: |
    apt-get install sudo
    apt install sudo wget postgresql postgresql-contrib curl unzip git
  displayName: 'Install deps'

- script: |
    cd install
    ./install_db.sh
  displayName: 'Install DB'
