# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- ci

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    ubuntu18:
      containerImage: geonature/ubuntu:18.04
    debian9:
      containerImage: geonature/debian:stretch
    debian10:
      containerImage: geonature/debian:buster
      
container: $[ variables['containerImage'] ]

steps:

- script: |
    sed -i 's|mon.domaine.com|127.0.0.1|' install/install_all/install_all.ini
    sed -i 's|install_sig_layers=true|install_sig_layers=false|' install/install_all/install_all.ini
    sed -i 's|install_grid_layer=true|install_grid_layer=false|' install/install_all/install_all.ini
    sed -i 's|install_default_dem=true|install_default_dem=false|' install/install_all/install_all.ini
  displayName: 'Settings'
 
- bash: |
    cat /etc/*-release
    id
  displayName: 'informations'

- bash: |
    sudo apt update -y
  displayName: 'apt update'

# - bash: |
#     sudo apt install wget -y 
#   displayName: 'test apt install wget'

# - bash: |
#     sudo apt install wget postgresql postgresql-contrib curl unzip git -y
#   displayName: 'Install deps'

- bash: |
    cd install/install_all
    echo ./install_all.sh
  displayName: 'Install All'

